services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas-multi-tenant-rbac
    ports:
      - "5432:5432"
#PGPASSWORD=postgres pg_dump -h localhost -p 5432 -U postgres clinic-multi-tenant > backup.sql
