### Criar usuário
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Helton",
  "email": "helton@acme.com",
  "password": "123456"
}


###

### Criar usuário
POST http://localhost:3333/sessions/password
Content-Type: application/json

{
  "email": "helton@acme.com",
  "password": "123456"
}
